# Future Actions

The package will be extended to include fundamental modules for modelling research. One of the future goals is to include Partial Differential Equations (PDEs) to explore the spatial dynamics of systems. Stability analysis and numerical simulations of PDEs will be included. Discrete models such as Markov chain and Individual-Based Models (IBMs, sometimes known as agent-based modelling) will also be included. In this way, users are allowed to choose a variety of modelling frameworks for intercomparison. 

As a tool for ecological research, ‘ecode’ package will also extend its application modules to benefit biodiversity and earth system scientists. Community ecology models will be integrated for users working on species conservation and biodiversity management. Useful theories such as species–area relationships, island biogeography, and metacommunity dynamics are critical to determine the level of endangered species. Functional ecologists are interested in how biogeochemicals move inside the earth system. Building blocks of Earth System Models (ESMs) will be integrated into the package to simulate these dynamics. These include photosynthesis, plant hydraulics, respiration, and carbon allocation. Integrating mass and energy flow in soils, atmosphere, and ocean will be a further goal. In this way, ‘ecode’ package will become a flexible tool for modellers to develop ESMs of appropriate scale and complexity. This will benefit the international carbon auditing, such as the IPCC report. Finally, the package may integrate process-based biodiversity models, benefiting rewilding and nature recovery activities at a UN decade of restoration. 
