# Welcome {-}

`ecode`, a novel package for modelling ecological populations and communities using ordinary differential equation systems, designed with a user-friendly framework. 

By following a three-cycle procedure, users can easily construct ecological models and explore their behaviors through a wide range of graphical, analytical, and numerical techniques. 

The package incorporates advanced techniques such as grid search methods and simulated annealing algorithms, enabling users to iteratively refine their models and achieve accurate predictions. 

Notably, ecode minimises external dependencies, ensuring robustness and reducing the risk of package failure caused by updates in dependencies. 

## Citation {-}

To cite `ecode` in publications use:

Haoran Wu,
ecode: An R package to investigate community dynamics in ordinary differential equation systems,
Ecological Modelling,
2024,
<https://doi.org/10.1016/j.ecolmodel.2024.110676>.


## Installation {-}

You can install the released version of `ecode` from
[CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ecode")
```

You can install the development version of `ecode` from
[GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("HaoranPopEvo/ecode")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
